version: '3'

services:
    rails:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        links:
            - db
    db:
        image: postgres:9.6.5
